server:
  port: 7006
spring:
  application:
    name: config-server #配置服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  cloud:
    #配置consul
    #consul:
    #host: localhost
    #port: 8500
    #discovery:
    #hostname: 127.0.0.1
        #健康检查
    #healthCheckPath: /health
    #healthCheckInterval: 15s
    #instance-id: id-config-server
    # 配置中心git仓库
    config:
      enabled: true
      server:
        git:
          #配置git仓库的地址
          uri:  https://github.com/a464570362/spring-clound-config
          search-paths:  config-repo
          username:  350218616@qq.com
          password:  shuai515515github
          # 强制获取覆盖
          force-pull: true
          # 不对服务器SSL 证书进行验证
          skip-ssl-validation: true
          #设置超时时间是4秒
          timeout: 4
          # 删除存储库中未跟踪的分支
          delete-untracked-branches: true
management:
  endpoints:
    web:
      exposure:
        include: "*"